<!-- Blog Invalid input Contact Form  -->


<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel {#panelColor}">
        <div class="panel-heading">
            <h3 class="panel-title">{#panel}</h3>
        </div>
        <div class="panel-body">
            <a href="/Contact/show">
                <button class="btn btn-lg btn-primary btn-block" type="button">{#button}</button>
            </a>
                </fieldset>
            </form>

        </div>
    </div>
</div>
<!-- End of  Blog Contact Form  -->