<!-- Blog Contact Form  -->

                <fieldset>
                    <div class="container"><br><br>
                        <div class="col-md-4">
                            <div class="alert alert-success">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <strong>  Raychev </strong>
                                        <div class="text-capitalize">Self-Employed Teamaker</div>
                                        <a href="https://github.com/RAYCHEV">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/raychev">Softuni</a><br>
                                        <a href="http://nraychev.wordpress.com">nraychev.wordpress.com</a>
                                    </div>
                                </div>
                                <a href="/Contact/message/Raychev" ><button type="button" class="btn btn-success btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="alert alert-danger">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <b> Ivanka </b>
                                        <div class="text-capitalize">developer</div>
                                        <a href="https://github.com/VaniaStoicheva">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/vanina">Softuni</a><br>
                                        <br>
                                    </div>
                                </div>
                                <a href="/Contact/message/Ivanka"><button type="button" class="btn btn-danger btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="alert alert-warning">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <b> Dimitar </b>
                                        <div class="text-capitalize">developer</div>
                                        <a href="https://github.com/Dimitarsgit">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/dimitars">Softuni</a><br>
                                        <br>
                                    </div>
                                </div>
                                <a href="/Contact/message/Dimitar"><button type="button" class="btn btn-warning btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="alert alert-info">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <div><strong>Martin</strong> </div>
                                        <div><em>Likes to make his life hard!</em></div>
                                        <div class="text-capitalize">developer</div>
                                        <a href="https://github.com/worminer">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/worminer">Softuni</a><br>
                                        <br>
                                    </div>
                                </div>
                                <a href="/Contact/message/Martin"><button type="button" class="btn btn-info btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="alert alert-warning">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <b> Villy </b><br>
                                        <div class="text-capitalize">developer</div>
                                        <a href="https://github.com/Villy">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/villyjord">Softuni</a><br>
                                        <br>
                                    </div>
                                </div>
                                <a href="/Contact/message/Villy"><button type="button" class="btn btn-success btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="alert alert-danger">
                                <div class="panel-body">
                                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                                    <div class="biz_cart">
                                        <b> Stefan </b><br>
                                        <div class="text-capitalize">developer</div>
                                        <a href="https://github.com/SKT3">Github</a><br>
                                        <a href="https://softuni.bg/users/profile/show/karadjov">Softuni</a><br>
                                        <br>
                                    </div>
                                </div>
                                <a href="/Contact/message/Stefan"><button type="button" class="btn btn-info btn-xs btn_cart">Send me a message</button></a>
                            </div>
                        </div>
                    </div>
                </fieldset>

<!-- End of  Blog Contact Form  -->