<!-- Blog Contact Form  -->

<fieldset>
    <div class="container"><br><br>


        <div class="col-md-4">
            <div class="alert alert-success">
                <div class="panel-body">
                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <strong>  Raychev </strong><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Raychev" ><button type="button" class="btn btn-success btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>


        <div class="col-md-4">
            <div class="alert alert-danger">
                <div class="panel-body">
                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <b> Ivanka </b><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Ivanka"><button type="button" class="btn btn-danger btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>

        <div class="col-md-4">
            <div class="alert alert-warning">
                <div class="panel-body">
                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <b> Dimitar </b><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Dimitar"><button type="button" class="btn btn-warning btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>

        <div class="col-md-4">
            <div class="alert alert-info">
                <div class="panel-body">
                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <b> Martin </b><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Martin"><button type="button" class="btn btn-info btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>



        <div class="col-md-4">
            <div class="alert alert-warning">
                <div class="panel-body">
                    <img s12rc="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <b> Villy </b><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Villy"><button type="button" class="btn btn-success btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>

        <div class="col-md-4">
            <div class="alert alert-danger">
                <div class="panel-body">
                    <img src="https://www.codeschool.com/assets/paths/badge-php-84d37c006e1829f8afa73aca97f3d03b6c9eff90f25e8375e9143cc186ed2e1f.svg" class="avatar_pic img-thumbnail"/>
                    <div class="biz_cart">
                        <b> Stefan </b><br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                        Info about me<br>
                    </div>
                </div>
                <a href="/Contact/message/Stefan"><button type="button" class="btn btn-info btn-xs btn_cart">Send me a message</button></a>
            </div>
        </div>


    </div>
</fieldset>

<!-- End of  Blog Contact Form  -->