
<div class="col-md-6 col-md-offset-3">
    <div class="login-panel panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">Delete category</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="/categories/deletePost/{#id}">
                <fieldset>
                    <div class="form-group col-md-12"  >
                        <strong>Are you sure you want to delete this Category ?</strong>
                    </div>

                    <div class="form-group col-md-6"  >
                        <input class="form-control" name="title" type="text" value="{#name}" disabled="disabled" autofocus required>
                    </div>
                    <div class="form-group col-md-6"  >
                        <input type="submit" class="btn btn-danger btn-block" name="delete_category" value="Delete!">
                    </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>
