<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{@site_title}
        {{#if sub_title}}
            &nbsp;-&nbsp;{#sub_title}
        {{/if}}

    </title>

    <!-- Bootstrap Core CSS -->
    <link href="/resources/css/bootstrap.Cerulean.min.css" rel="stylesheet">
    <!-- Font Awasome CSS -->
    <link href="/resources/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/resources/css/blog-main.css" rel="stylesheet">
    <!-- /.container -->
    <!-- jQuery -->
    <script src="/resources/javascript/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/resources/javascript/bootstrap.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>