<!-- Blog Search Well -->
<div class="well">
    <h4>Blog Search</h4>
    <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
    </div>
    <!-- /.input-group -->
</div>

<!-- Blog Categories Well -->

<div class="well">
    <h4>Blog Categories</h4>
    <div class="row">
        <div class="col-lg-12">
            {{#if categoryInfo}}
            <ul class="list-group">

                {{#each categoryInfo}}
                <li class="list-group-item">
                    <a class=" list-group-item" href="/categories/showCategoryId/{{value['id']}}">
                        <span class="badge">{{value['articlesCount']}}</span>
                        <span><b>{{value['name']}}</b></span>
                    </a>
                </li>
                {{/each}}
            </ul>
            {{else}}
                <strong>There are no categories at the moment!</strong>
            {{/if}}

        </div>

    </div>
    <!-- /.row -->
</div>
