<!-- Blog Search Well -->
<div class="well">
    <h4>Blog Search</h4>
    <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
    </div>
    <!-- /.input-group -->
</div>

<!-- Blog Categories Well -->

<div class="well">
    <h4>Blog Categories</h4>
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled">
               <li>
                   <a href="">
                       <img class="category-img" style="width: 60px;margin: 0 auto;"
                            src="http://cdn.iflscience.com/assets/site/img/icon-environment.png?v=1.2.0" alt="Environment">
                       <span><b>Nature</b></span>
                   </a>
               </li>
                <li>
                    <a href="">
                        <img class="category-img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-technology.png?v=1.2.0" alt="Technology">
                        <span><b>Tech</b></span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img class="category_img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-space.png?v=1.2.0" alt="Space">
                        <span><b>Space</b></span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img class="category_img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-health-and-medicine.png?v=1.2.0" alt="Health">
                        <span><b>Health</b></span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.col-lg-6 -->
        <div class="col-lg-6">
            <ul class="list-unstyled">
                <li>
                    <a href="">
                        <img class="category_img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-the-brain.png?v=1.2.0" alt="The Brain">
                        <span><b>The Brain</b></span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img class="category_img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-plants-and-animals.png?v=1.2.0" alt="Plants and Animals">
                        <span><b>Animals</b></span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img class="category_img"style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-physics.png?v=1.2.0" alt="Physics">
                        <span><b>Physics</b></span>
                    </a>
                </li>
                <li>
                    <a href="">
                        <img class="category_img" style="width: 60px;margin: 0 auto;"
                             src="http://cdn.iflscience.com/assets/site/img/icon-chemistry.png?v=1.2.0" alt="Chemistry">
                        <span><b>Chemistry</b></span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
</div>

<!-- Side Widget Well -->
<div class="well">
    <h4>Side Widget Well</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
</div>