<div class="col-md-12">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
             <a class="nav navbar-brand" href="#"><img style="max-width: 70px"  src="/resources/images/logo.jpg"></a>
            <!-- <a class="navbar-brand" href="#" title="blog">
                 <img style="width:50px; "
                      src="/resources/images/logo.jpg">-->
         </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">Home</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="/contact/show">Contact</a>
                </li>
                <li>
                    <a href="/article/create">Create new Post</a> <!-- Show only when logged in as Editor -->
                </li>
                <li>
                    <a href="/article/allPost">Show All Post</a> <!-- Show only when logged in as Guest -->
                </li>
                <li>
                    <a href="/article/show">My Posts</a> <!-- Show only when logged in as Editor -->
                </li>

                <li class="dropdown"> <!-- Show only when logged in as Admin -->
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin Panel
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/allusers">Users</a></li>
                        <li><a href="#">Articles</a></li>
                        <li><a href="#">Category</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav pull-right">
                <li> <a href="/user/login">
                        <span class="glyphicon glyphicon-log-in"> </span>
                        Login</a></li>
                <li> <a href="/user/register">
                        <span class="glyphicon glyphicon-user"> </span>
                        Register</a></li>
                <li> <a href="/user/logout">
                        <span class="glyphicon glyphicon-log-out"> </span> <!-- Show only when logged in-->
                        Logout</a></li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->

        <!-- /.container -->
    </nav>
</div>
