{>header}
<body>
<!-- Navigation -->
<div class="container">
    <div class="row">
        {>topNav}
    </div>
</div>
<!-- MessageBox -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
        {>messageBox}
        </div>
    </div>
</div>
<!-- Body -->
<div class="container">
    <div class="row">
        <div class="col-md-12">
            {%body%}
        </div>
    </div>
</div>
<!-- /.Body -->

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-md-12">
            {>footer}
        </div>
    </div>
</footer>
</body>
</html>

