<!-- Blog Login Form  -->
<div class="col-md-6 col-md-offset-3">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">New Category</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="addPost">
                <fieldset>

                    <div class="form-group col-md-6"  >
                        <input class="form-control" placeholder="Category Name" name="title" type="text" autofocus required>

                    </div>
                    <div class="form-group col-md-6"  >
                        <input class="btn btn-success btn-block" type="submit" value="Create new Category" name="create" >
                    </div>



                </fieldset>
            </form>
        </div>
    </div>


</div>
<div class="col-md-10 col-md-offset-1">
    <table class="table table-striped table-hover ">
        <thead>
        <tr>
            <th>#</th>
            <th>Database Id</th>
            <th>Category name</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Column content</td>
            <td>Column content</td>
        </tr>

        </tbody>
    </table>
</div>

<!-- End of  Blog Login Form  -->