<!-- Blog Login Form  -->
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Sign In</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="/user/loginPost">
                <fieldset>
                    <div class="form-group"  >
                        <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus required>
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Password" name="password" type="password" value="" required>
                    </div>
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="login" name="login" >
                </fieldset>
            </form>
            <hr>
            <span>You don't have an account? <a href="/user/register"><b>Register here!</b></a></span>
        </div>
    </div>
</div>
<!-- End of  Blog Login Form  -->
