<!-- Blog Login Form  -->
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Registration</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="/user/registerPost">
                <fieldset>
                    <div class="form-group"  >
                        <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus required>
                    </div>
                    <div class="form-group"  >
                        <input class="form-control" placeholder="Display name" name="real_name" type="real_name"  required>
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Password" name="password" type="password" value="" required>
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Repeat Password" name="password2" type="password" value="" required>
                    </div>
                    <input class="btn btn-lg btn-primary btn-block" type="submit" value="Register" name="register" >
                </fieldset>
            </form>

        </div>
    </div>
</div>
<!-- End of  Blog Login Form  -->