<!-- Blog Login Form  -->
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">New Article</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="createPost">
                <fieldset>

                    </div>
                    <div class="form-group"  >
                        <input class="form-control" placeholder="Article Title" name="title" type="text" autofocus required>
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" placeholder="Article Content" name="content" type="text"  required></textarea>
                    </div>
                    <input class="btn btn-lg btn-success btn-block" type="submit" value="Create new article" name="create" >
                </fieldset>
            </form>
        </div>
    </div>
</div>

<!-- End of  Blog Login Form  -->