<!-- Blog Show  -->
<div class="col-md-8 col-md-offset-2">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Edit Post</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post" action="/article/editPost/{#article_id}">
                <fieldset>
                    <div class="form-group"  >
                        <input type="hidden" name="id" value="{#article_id}">
                        <input class="form-control" type="text" name="title" value="{#title}" autofocus required>
                    </div>
                    <div class="form-group">
                        <textarea name="content" id="" cols="95" rows="10">{#content}</textarea>
                    </div>
                    <input class="btn btn-lg btn-success btn-block" type="submit" value="Edit post" name="editArticle" >
                </fieldset>
            </form>

        </div>

    </div>

<!-- End of  Blog Show  -->