<!-- Blog Show  -->
<div class="col-md-12 ">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">My Articles </h3>
        </div>
        <div class="panel-body">
            {{#if results}}
                {{#each results}}
                    <div class="panel-body panel-collapse">
                        <div class="well">
                            <span class="well">
                                <b> Tile:</b>  {{value["title"]}}
                            </span>
                            <span class="well pull-right">
                                <b> Writen by:</b>  {{value["real_name"]}}
                            </span>
                            <div class="well">
                                {{value["content"]}}
                            </div>
                            <div class="well pull-right">
                               <b>Written at:</b> {{value["created_at"]}}
                            </div>
                            <div class="well pull-left">
                                <a href="/article/edit/{{value["article_id"]}}" class="btn btn-primary btn-sm">Edit</a>
                                <a href="/article/delete/{{value["article_id"]}}" class="btn btn-primary btn-sm">Delete</a>
                            </div>
                        </div>
                    </div>
                {{/each}}
            {{else}}
             Sorry, you don't have any articles to show!
            {{/if}}
        </div>
    </div>
</div>

<!-- End of  Blog Show  -->