<!-- Blog Show  -->
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">View Post </h3>
        </div>
        <div class="panel-body panel-success">
            {{#each results}}
            <div class="panel-body panel-collapse">
                <blockquote>{{value["username"]}}</blockquote>
            <li>{{value["title"]}}</li>
            <li>{{value["content"]}}</li>
            <a href="/article/edit/{{value["article_id"]}}" class="btn btn-primary btn-sm">Edit</a>
            <a href="/article/delete/{{value["article_id"]}}" class="btn btn-primary btn-sm">Delete</a>

            </div>
            {{/each}}

        </div>

        </div>


<!-- End of  Blog Show  -->