<!-- Blog Login Form  -->
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">View Post</h3>
        </div>
        <div class="panel-body">


        {#results}
                {{#each results}}
        <p>{{key}} --> {{value}}</p>

        {{/each}}

        </div>
    </div>
</div>
<?php
var_dump($_POST);
?>
<!-- End of  Blog Login Form  -->