<!-- Blog Entries Column -->

<div class="col-md-8">
    <div class="well">
        <h1>Welcome to our cool blog system</h1>

        <a href="Action/checkLogin/">Login</a>

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="/user/register"> <!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345"> <!-- Article Image Path -->
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <a href=""> <!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

                <div class="item">
                    <a href=""><!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

                <div class="item">
                    <a href="">
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>


        <!-- Articles (za kolejkata :D) -->
        <div class="item">
            <script src="/resources/tinymce/tinymce.min.js"></script>
            <script>tinymce.init({ selector:'textarea' });</script>

            <form class="form-horizontal" method="post" accept-charset="UTF-8">
                <h5></h5>

                <label class="control-label" for="title">Title</label>
                <input class="form-control" type="text" name="title" maxlength="300"/><br/>

                <textarea class="content" name="body"></textarea>
                <br/>

                <button class="btn btn-primary btn-success pull-left" type="submit" name="submit" >
                    <span class="glyphicon glyphicon-plus-sign"> <b>Create</b></span></button>

            </form>
        </div>
        <!-- Articles (za kolejkata :D) -->

    </div>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
    {>sidebar}
</div>