<!-- Blog Entries Column -->

<div class="col-md-8">
    <div class="well">
        <h1>Welcome to our cool blog system</h1>

        <a href="Action/checkLogin/">Login</a>

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <a href="/user/register"> <!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345"> <!-- Article Image Path -->
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>
                <div class="item">
                    <a href=""> <!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

                <div class="item">
                    <a href=""><!-- Article Path -->
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

                <div class="item">
                    <a href="">
                        <img src=""
                             alt="no picture" width="460" height="345">
                        <div class="carousel-caption">
                            <h3>"Article Name"</h3>
                            <p>"Resume about the article /or smth"</p>
                        </div>
                    </a>
                </div>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
    {>sidebar}
</div>