<div class="col-md-8 col-md-offset-2">
    <div class="login-panel panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Edit User</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="post">
                <fieldset>
                    <div class="row user-infos cyruxx">
                        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    <h3 class="panel-title">User information</h3>
                                </div>
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="col-md-3 col-lg-3 hidden-xs hidden-sm">
                                            <img class="img-circle"
                                                 src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100"
                                                 alt="User Pic">
                                        </div>
                                        <div class="col-xs-2 col-sm-2 hidden-md hidden-lg">
                                            <img class="img-circle"
                                                 src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=50"
                                                 alt="User Pic">
                                        </div>
                                        <div class="col-xs-10 col-sm-10 hidden-md hidden-lg">

                                            <label class="control-label" for="title"><b>Username</b></label>
                                            <input class="form-control" type="text" name="username"
                                                   maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>User Role</b></label>
                                            <input class="form-control" type="text" name="user_role"
                                                   value="" maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>Real Name</b></label>
                                            <input class="form-control" type="text" name="real_name"
                                                   value="" maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>Email</b></label>
                                            <input class="form-control" type="text" name="email"
                                                   value="" maxlength="300"/><br/>

                                        </div>
                                        <div class=" col-md-9 col-lg-9 hidden-xs hidden-sm">
                                            <label class="control-label" for="title"><b>Username</b></label>
                                            <input class="form-control" type="text" name="username"
                                                   value="" maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>User Role</b></label>
                                            <input class="form-control" type="text" name="user_role"
                                                   value="" maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>Real Name</b></label>
                                            <input class="form-control" type="text" name="real_name"
                                                   value="" maxlength="300"/><br/>
                                            <label class="control-label" for="title"><b>Email</b></label>
                                            <input class="form-control" type="text" name="email"
                                                   value="" maxlength="300"/><br/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <input class="btn btn-lg btn-success btn-block" type="submit" value="Edit post" name="edit">
                </fieldset>
            </form>

        </div>

    </div>


