<!-- Blog Entries Column -->
<div class="col-md-8">
    <div class="well">
        <h1>in this page you can see example usage of templates</h1>

        <h2>example of if template logic</h2>
        <div>
            if variable with name is given then it will check if its true or false
            and if it is true then will display the block and if it is false it will
            display an empty string
            <br>
            <br>
            {{#if first}}
            if true do this else do nothing
            {{/if}}
        </div>
        <hr>
        <hr>
        <div>
            <h2>example of if else template logic</h2>
            if variable with name is given then it will check if its true or false
            and if it is true then will display the block from if to else
            and if it is false will display the else to /if
            <br>
            <br>
            {{#if first}}
                if true do this
            {{else}}
                else do this
            {{/if}}
        </div>
        <hr>
        <div >
            <h2>how to display variables send from controller</h2>
            {#stringVariable}   - will display the variable, if it is a string, int or float it will be displayed as string<br>
            {#boolVariable}     - will display the variable, if the variable is type bool then will be converted to string true/false<br>
            {#arrayVariable}    - will display the variable, if it is an array it will be inploded to string<br>
        </div>
        <hr>
    </div>
</div>
<!-- Blog Sidebar Widgets Column -->
<div class="col-md-4">
    {>sidebar}
</div>